services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: hanas-cobblemon-pack
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 25002:25565
      - 26002:26002
    depends_on:
      restore-backup:
        condition: service_completed_successfully
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "LATEST"
      SEED: "467777518361797585"
      WHITELIST: "TRUE"
      DIFFICULTY: "HARD"
      ALLOW_FLIGHT: "TRUE"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "26002"
      RESOURCE_PACK: "https://files.jadelily.dev/r3q5Fz5fWXMubLZqWfcO.zip"
      RESOURCE_PACK_SHA1: "baee26b692bf2f6240288f4c0d9485eb236e7914"
      RESOURCE_PACK_ENFORCE: "TRUE"
      # Pack might not update properly so we specify the version instead of the slug or base url
      MODRINTH_MODPACK: "https://modrinth.com/modpack/hanas-cobblemon-pack/version/1.6.19"
      # Athena is required for Chipped to work, and Deimos is required for EXP Counter
      MODRINTH_PROJECTS: |
        deimos
        athena-ctm
        fabric-api
        styled-chat
        styled-nicknames
        styledplayerlist
        mod-viewer
        banhammer
        player-pronouns
        spark
        worldedit
      MODRINTH_FORCE_SYNCHRONIZE: "TRUE"
      MEMORY: "8G"
    volumes:
      - ./data:/data
      - ./config:/config
  backup:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      RCON_PORT: 26002
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: 6h
      TZ: "America/Chicago"
      PRUNE_BACKUPS_DAYS: 14
    volumes:
      - ./data:/data:ro
      - /mnt/data/minecraft/backups/hanas-cobblemon-pack:/backups
  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - /mnt/data/minecraft/backups/hanas-cobblemon-pack:/backups:ro
