services:
  router:
    image: itzg/mc-router
    container_name: mc-router
    command: "-in-docker"
    ports:
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: minecraft
