services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-dev-testing
    tty: true
    stdin_open: true
    env_file: .env
    networks:
      - minecraft
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "LATEST"
      WHITELIST: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "password"
      RCON_PORT: "26010"
      MODRINTH_MODPACK: "adrenaline"
      MODRINTH_PROJECTS: |
        mod-viewer
        spark
      MEMORY: "2G"
    labels:
      mc-router.host: "${MC_ROUTER_HOST}"
    volumes:
      - ./data:/data

networks:
  minecraft:
    external: true
    name: minecraft
