version: "3"

services:
    fabric-server:
        image: itzg/minecraft-server
        ports:
            - 20001:20001
        environment:
            EULA: "TRUE"
            VERSION: "1.19.2"
            TYPE: "FABRIC"
            DIFFICULTY: "HARD"
            SERVER_NAME: "A Fabric Server"
            SERVER_PORT: "20001"
            MOTD: "§fA Fabric server!"
            ICON: "https://raw.githubusercontent.com/jadelily18/docker-servers/main/docker-compose/basic-fabric/data/server-icon.png"
            PACKWIZ_URL: "https://raw.githubusercontent.com/jadelily18/jades-server-pack/master/pack.toml"
            ALLOW_FLIGHT: "TRUE"
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            # attach a directory relative to the directory containing this compose file
            - ./minecraft-data:/data
