services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-basic-backup-example
    tty: true
    stdin_open: true
    env_file:
      - .env.example
    ports:
      - 24000:25565
    depends_on:
      restore-backup:
        condition: service_completed_successfully
    environment:
      EULA: "TRUE"
      MODRINTH_MODPACK: "ADRENALINE"
      MODRINTH_PROJECTS: |
        fabric-api
        fabric-permissions-api
        styled-chat
      VERSION: "LATEST"
      TYPE: "FABRIC"
      MEMORY: "3G"
    volumes:
      - ./data:/data
      - ./config:/config
  backup:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: 6h
    volumes:
      - ./data:/data
      - /mnt/data/minecraft/backups/basic-backup:/backups
  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - /mnt/data/minecraft/backups/basic-backup:/backups
