services:
  mc:
    image: itzg/minecraft-server
    container_name: worlds-together
    user: "1000"
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - 25001:25565
    depends_on:
      restore-backup:
        condition: service_completed_successfully
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "LATEST"
      MODRINTH_MODPACK: "worlds-together"
      MODRINTH_PROJECTS: |
        fabric-api
        fabric-permissions-api
        styled-chat
      MEMORY: "6G"
    volumes:
      - ./data:/data
      - ./config:/config
  backup:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: 6h
      TZ: "America/Chicago"
      PRUNE_BACKUPS_DAYS: 14
    volumes:
      - ./data:/data:ro
      - /mnt/data/minecraft/backups/worlds-together:/backups
  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - /mnt/data/minecraft/backups/worlds-together:/backups:ro
